//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolyclinicDBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoctorsTimeTable
    {
        public int id { get; set; }
        public int SpecId { get; set; }
        public string Shedule { get; set; }
        public int Interval { get; set; }
    
        public virtual Specialization Specialization { get; set; }
    }
}
