//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolyclinicDBManager
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PolyclinicDBContext : DbContext
    {
        public PolyclinicDBContext()
            : base("name=PolyclinicDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Diagnosis> Diagnosis { get; set; }
        public virtual DbSet<Doctor> Doctor { get; set; }
        public virtual DbSet<DoctorsTimeTable> DoctorsTimeTable { get; set; }
        public virtual DbSet<Drug> Drug { get; set; }
        public virtual DbSet<Login> Login { get; set; }
        public virtual DbSet<Patient> Patient { get; set; }
        public virtual DbSet<Region> Region { get; set; }
        public virtual DbSet<Room> Room { get; set; }
        public virtual DbSet<Specialization> Specialization { get; set; }
        public virtual DbSet<Street> Street { get; set; }
        public virtual DbSet<Ticket> Ticket { get; set; }
        public virtual DbSet<VisitorStatistics> VisitorStatistics { get; set; }
    }
}
