//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolyclinicDBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitorStatistics
    {
        public int DocId { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> ArrivedPatients { get; set; }
        public Nullable<int> NonArrivedPatients { get; set; }
    
        public virtual Doctor Doctor { get; set; }
    }
}
